/**
 * @alfred/forge - Skill Templates
 *
 * Template strings for generating the files that make up a forged skill:
 * SKILL.md, index.ts, test.ts, fallbacks.ts, and package.json.
 *
 * Uses simple {{variable}} interpolation.
 */

// ---------------------------------------------------------------------------
// Template interpolation
// ---------------------------------------------------------------------------

/**
 * Replace all `{{key}}` placeholders in a template with values from `vars`.
 * Unknown placeholders are left as-is.
 */
export function fillTemplate(
  template: string,
  vars: Record<string, string>,
): string {
  return template.replace(/\{\{(\w+)\}\}/g, (match, key: string) => {
    return Object.prototype.hasOwnProperty.call(vars, key) ? vars[key] : match;
  });
}

// ---------------------------------------------------------------------------
// SKILL.md
// ---------------------------------------------------------------------------

export function getSkillMdTemplate(): string {
  return `# {{skillName}}

> Auto-forged by Alfred Forge on {{createdAt}}

## Description

{{description}}

## Category

{{category}}

## Complexity

{{complexity}}

## Tools

{{toolsDocs}}

## Parameters

{{paramsDocs}}

## Dependencies

{{dependencies}}

## Test Cases

{{testCasesDocs}}

## Origin

- **Gap ID**: {{gapId}}
- **Confidence**: {{confidence}}
- **Frequency**: {{frequency}}
- **Status**: forged (sandbox-only)
`;
}

// ---------------------------------------------------------------------------
// index.ts  (main skill entry point)
// ---------------------------------------------------------------------------

export function getIndexTemplate(): string {
  return `/**
 * {{skillName}} - Auto-forged skill
 *
 * {{description}}
 *
 * Generated by @alfred/forge on {{createdAt}}
 * Status: forged (sandbox-only until promoted)
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

{{toolTypes}}

// ---------------------------------------------------------------------------
// Tool implementations
// ---------------------------------------------------------------------------

{{toolImplementations}}

// ---------------------------------------------------------------------------
// Skill manifest
// ---------------------------------------------------------------------------

export const manifest = {
  name: '{{skillName}}',
  version: '1.0.0',
  description: '{{description}}',
  category: '{{category}}',
  tools: [{{toolNames}}],
  status: 'forged' as const,
  sandbox: true,
};

export default manifest;
`;
}

// ---------------------------------------------------------------------------
// test.ts
// ---------------------------------------------------------------------------

export function getTestTemplate(): string {
  return `/**
 * {{skillName}} - Auto-generated tests
 *
 * Generated by @alfred/forge on {{createdAt}}
 */

{{testImports}}

// ---------------------------------------------------------------------------
// Test cases
// ---------------------------------------------------------------------------

{{testCases}}

// ---------------------------------------------------------------------------
// Test runner (standalone)
// ---------------------------------------------------------------------------

interface TestResult {
  name: string;
  passed: boolean;
  error?: string;
}

export async function runTests(): Promise<TestResult[]> {
  const results: TestResult[] = [];

{{testRunner}}

  return results;
}

// Self-execute when run directly
const isMainModule =
  typeof process !== 'undefined' &&
  typeof process.argv !== 'undefined' &&
  process.argv[1] &&
  (process.argv[1].endsWith('test.ts') || process.argv[1].endsWith('test.js'));

if (isMainModule) {
  runTests().then((results) => {
    const passed = results.filter((r) => r.passed).length;
    const failed = results.filter((r) => !r.passed).length;
    console.log(\`\\nResults: \${passed} passed, \${failed} failed\`);
    if (failed > 0) {
      console.log('\\nFailed tests:');
      for (const r of results.filter((r) => !r.passed)) {
        console.log(\`  - \${r.name}: \${r.error}\`);
      }
      process.exit(1);
    }
  });
}
`;
}

// ---------------------------------------------------------------------------
// fallbacks.ts
// ---------------------------------------------------------------------------

export function getFallbacksTemplate(): string {
  return `/**
 * {{skillName}} - Fallback strategies
 *
 * When the primary tool implementation fails, these fallbacks
 * provide degraded-but-functional alternatives.
 *
 * Generated by @alfred/forge on {{createdAt}}
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface FallbackResult<T = unknown> {
  success: boolean;
  data?: T;
  error?: string;
  fallbackUsed: string;
}

export interface FallbackStrategy {
  name: string;
  description: string;
  execute: (input: unknown) => Promise<FallbackResult>;
}

// ---------------------------------------------------------------------------
// Fallback registry
// ---------------------------------------------------------------------------

const fallbacks: Map<string, FallbackStrategy[]> = new Map();

/**
 * Register a fallback strategy for a tool.
 */
export function registerFallback(toolName: string, strategy: FallbackStrategy): void {
  const existing = fallbacks.get(toolName) ?? [];
  existing.push(strategy);
  fallbacks.set(toolName, existing);
}

/**
 * Execute fallbacks for a tool in order until one succeeds.
 */
export async function executeFallbacks(
  toolName: string,
  input: unknown,
): Promise<FallbackResult> {
  const strategies = fallbacks.get(toolName) ?? [];

  for (const strategy of strategies) {
    try {
      const result = await strategy.execute(input);
      if (result.success) return result;
    } catch {
      // Strategy failed, try next
    }
  }

  return {
    success: false,
    error: \`All \${strategies.length} fallback strategies for "\${toolName}" exhausted\`,
    fallbackUsed: 'none',
  };
}

// ---------------------------------------------------------------------------
// Default fallback strategies for {{skillName}}
// ---------------------------------------------------------------------------

{{fallbackStrategies}}

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

export { fallbacks };
`;
}

// ---------------------------------------------------------------------------
// package.json
// ---------------------------------------------------------------------------

export function getPackageJsonTemplate(): string {
  return `{
  "name": "{{packageName}}",
  "version": "1.0.0",
  "type": "module",
  "private": true,
  "description": "{{description}}",
  "main": "index.ts",
  "scripts": {
    "test": "node --loader ts-node/esm test.ts"
  },
  "alfred": {
    "skill": true,
    "category": "{{category}}",
    "status": "forged",
    "sandbox": true,
    "forgedAt": "{{createdAt}}",
    "complexity": "{{complexity}}"
  }
}
`;
}
