/**
 * @alfred/playbook - Type definitions
 *
 * All interfaces and types used across the playbook package:
 * entries, strategies, patterns, stats, and reports.
 */

// ---------------------------------------------------------------------------
// Entry Types
// ---------------------------------------------------------------------------

/** The kind of event captured in the playbook. */
export type PlaybookEntryType =
  | 'tool_execution'
  | 'fallback'
  | 'forge_event'
  | 'error'
  | 'system';

/** Forge event subtypes that track the skill-generation lifecycle. */
export type ForgeEventType =
  | 'gap_detected'
  | 'plan_created'
  | 'build_started'
  | 'build_completed'
  | 'test_passed'
  | 'test_failed'
  | 'promoted'
  | 'quarantined';

/** A single playbook entry -- one logged event. */
export interface PlaybookEntry {
  id: string;
  type: PlaybookEntryType;
  timestamp: string;
  tool: string;
  args: unknown;
  result: unknown;
  error: string | null;
  durationMs: number;
  agentId: string;
  sessionId: string;
  channel: string | null;
  success: boolean;
  tags: string[];
}

// ---------------------------------------------------------------------------
// Strategy
// ---------------------------------------------------------------------------

/** An actionable strategy derived from playbook analysis. */
export interface Strategy {
  id: string;
  title: string;
  description: string;
  recommendations: string[];
  confidence: number;
  basedOn: string[];
  createdAt?: string;
  updatedAt?: string;
  source?: string;
  tags?: string[];
}

// ---------------------------------------------------------------------------
// Pattern
// ---------------------------------------------------------------------------

/** A detected pattern across playbook entries. */
export interface PlaybookPattern {
  id: string;
  type: string;
  description: string;
  frequency: number;
  firstSeen: string;
  lastSeen: string;
  data: Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// Stats
// ---------------------------------------------------------------------------

/** Aggregate statistics drawn from the playbook database. */
export interface PlaybookStats {
  totalEntries: number;
  successRate: number;
  topTools: Array<{ tool: string; count: number }>;
  topErrors: Array<{ error: string; count: number }>;
  entriesByDay: Array<{ date: string; count: number }>;
}

// ---------------------------------------------------------------------------
// Weekly Report
// ---------------------------------------------------------------------------

/** Weekly analysis report generated by the StrategyEngine. */
export interface WeeklyReport {
  period: string;
  totalOperations: number;
  successRate: number;
  topSuccesses: string[];
  topFailures: string[];
  newPatterns: string[];
  recommendations: string[];
}

// ---------------------------------------------------------------------------
// Search Options
// ---------------------------------------------------------------------------

/** Options for searching playbook entries. */
export interface SearchOptions {
  limit?: number;
  type?: PlaybookEntryType;
  since?: string;
}

// ---------------------------------------------------------------------------
// Database Row Types (internal)
// ---------------------------------------------------------------------------

/** Raw row shape returned by better-sqlite3 for entries. */
export interface EntryRow {
  id: string;
  type: string;
  timestamp: string;
  tool: string;
  args: string;
  result: string;
  error: string | null;
  duration_ms: number;
  agent_id: string;
  session_id: string;
  channel: string | null;
  success: number;
  tags: string;
}

/** Raw row shape returned by better-sqlite3 for strategies. */
export interface StrategyRow {
  id: string;
  title: string;
  description: string;
  created_at: string;
  updated_at: string;
  source: string | null;
  confidence: number;
  tags: string;
  recommendations: string;
  based_on: string;
}

/** Raw row shape returned by better-sqlite3 for patterns. */
export interface PatternRow {
  id: string;
  type: string;
  description: string;
  frequency: number;
  first_seen: string;
  last_seen: string;
  data: string;
}
